#!/usr/bin/env python3
"""
Assert the glossary page's quotes match the batch's own dictionary.

The Role definitions page claims its definitions are the CMS data
dictionary's, verbatim, and that when CMS revises one the page moves
with it. That is a claim about a future batch, and until 2026-08-31
nothing re-checked it: the quotes are hardcoded in lib/glossary.ts
while the dictionary rides in fresh with every zip. Principle 7 says
claim or check, and the founder ruled to build the check and keep the
claim (the review's WHAT 6).

So this reads the quoted definitions, the role values, and the stated
vintage out of lib/glossary.ts, extracts the text of the batch's
republished NH_Data_Dictionary.pdf, and asserts each appears in it.
Comparison is normalized (curly quotes and long dashes straightened,
whitespace collapsed, case folded) because PDF text extraction owns
none of those details; the page still shows the quotes as written.

On the fixture batch the PDF is generated by dev_fixture from this
module's own parse, so a fixture run proves the plumbing end to end
(parse, extract, normalize, compare) and deliberately cannot prove
freshness; the real batch's dictionary on the deploy path is the
freshness half. A PDF with no extractable text fails rather than
passing empty, which is also what the old fixture stand-in did the
first time this check ran.

    python3 scripts/check_glossary.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TS = ROOT / "lib" / "glossary.ts"
PDF = ROOT / "public" / "data" / "downloads" / "NH_Data_Dictionary.pdf"

QUOTED = r'"((?:[^"\\]|\\.)*)"'


def parse_glossary() -> tuple[list[tuple[str, str]], list[str], str]:
    """The terms, definitions, role values, and vintage hardcoded in
    lib/glossary.ts, or a loud failure: a parser that silently finds
    nothing would turn every later assertion vacuous."""
    src = TS.read_text(encoding="utf-8")
    defs_block = re.search(r"COLUMN_DEFINITIONS[^=]*=\s*\[(.*?)\n\];", src, re.S)
    roles_block = re.search(r"ROLE_VALUES[^=]*=\s*\[(.*?)\n\];", src, re.S)
    vintage = re.search(r"GLOSSARY_VINTAGE\s*=\s*" + QUOTED, src)
    if not (defs_block and roles_block and vintage):
        print("FAIL  could not locate COLUMN_DEFINITIONS, ROLE_VALUES, and "
              "GLOSSARY_VINTAGE in lib/glossary.ts; the file's shape changed "
              "and this parser must move with it")
        sys.exit(1)
    entries = re.findall(
        r"term:\s*" + QUOTED + r",\s*definition:\s*" + QUOTED,
        defs_block.group(1),
    )
    roles = re.findall(QUOTED, roles_block.group(1))
    if len(entries) < 3 or len(roles) < 10:
        print(f"FAIL  parsed only {len(entries)} definition(s) and "
              f"{len(roles)} role value(s) from lib/glossary.ts; that is "
              f"fewer than the file is known to hold, so the parser is "
              f"broken, not the glossary")
        sys.exit(1)
    return entries, roles, vintage.group(1)


def straighten(s: str) -> str:
    """Typographic characters replaced by their plain forms. Shared
    with the fixture's dictionary generator, whose base PDF font
    cannot encode the typographic ones; the comparison applies this
    to both sides, so the substitution changes nothing it proves."""
    return (s.replace("“", '"').replace("”", '"')
            .replace("‘", "'").replace("’", "'")
            .replace("–", "-").replace("—", "-")
            .replace("\u00a0", " "))


def normalize(s: str) -> str:
    return re.sub(r"\s+", " ", straighten(s)).strip().casefold()


def main() -> None:
    entries, roles, vintage = parse_glossary()
    if not PDF.exists():
        print(f"FAIL  {PDF.relative_to(ROOT)} is missing: every batch "
              f"republishes the dictionary, so a build without one has "
              f"nothing to hold the glossary against")
        sys.exit(1)
    import pymupdf

    doc = pymupdf.open(PDF)
    text = normalize(" ".join(page.get_text() for page in doc))
    if len(text) < 200:
        print("FAIL  the dictionary PDF yielded no extractable text, so "
              "nothing here can be verified; a check that cannot read its "
              "evidence must not pass")
        sys.exit(1)

    misses: list[str] = []
    for term, definition in entries:
        if normalize(definition) not in text:
            misses.append(f'definition of "{term}"')
    for role in roles:
        if normalize(role) not in text:
            misses.append(f'role value "{role}"')
    if normalize(vintage) not in text:
        misses.append(f'stated vintage "{vintage}"')

    if misses:
        print(f"FAIL  {len(misses)} glossary quote(s) not found in this "
              f"batch's dictionary:\n")
        for m in misses:
            print(f"  - {m}")
        print("\nCMS revised the dictionary, or the quotes drifted. Update "
              "lib/glossary.ts (and GLOSSARY_VINTAGE) to say what the "
              "dictionary now says; the page claims verbatim quotes and "
              "does not publish until that is true.")
        sys.exit(1)

    print(f"  ok    all {len(entries)} column definition(s) appear in the dictionary")
    print(f"  ok    all {len(roles)} role value(s) appear in the dictionary")
    print(f'  ok    the stated vintage ("{vintage}") appears in the dictionary')
    print("\nthe glossary says what the dictionary says")


if __name__ == "__main__":
    main()
